## One hot encoding with many variables
- dataset
- https://www.kaggle.com/aditya1702/mercedes-benz-data-exploration/data

In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('data/mercedesbenz.csv', usecols=['X1','X2'])

In [7]:
df.head(5)

  X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [8]:
#printing all the columns
for col in df:
    print(df[col].unique())

['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab']
['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar']

In [11]:
df['X1'].unique()

array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
       'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
       'ab'], dtype=object)

In [12]:
len(df['X1'].unique())

27

In [13]:
df['X2'].unique()

array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
       'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
       'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
       'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object)

In [14]:
len(df['X2'].unique())

44

In [15]:
## let's have a look how many labes each columns has
for col in df.columns:
    print(col, ':', len(df[col].unique()), 'labels')

X1 : 27 labels
X2 : 44 labels

In [17]:
df.shape

(4209, 2)

In [18]:
# let's examine how many columns we will obtain after one hot encoding these variables
pd.get_dummies(df, drop_first=True).shape

(4209, 69)



We can observe that from with just 2 categorical features we are getting 69 features with the help of one hot encoding.

## KDD Cup Orange Challenge

What can we do instead?

http://proceedings.mlr.press/v7/niculescu09/niculescu09.pdf
In the winning solution of the KDD 2009 cup: "Winning the KDD Cup Orange Challenge with Ensemble 

The Team suggested using 10 most frequent labels convert them into dummy variables using onehotencoding

How can we do that in python?

In [ ]:
#let's find the top most 10 frequent categories for the variable

In [23]:
df['X2'].value_counts().sort_values(ascending= False).head(10)

X2
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
ag      19
z       19
Name: count, dtype: int64

In [25]:
#let's make a list with the top most frequent categories of the variable
top_10_labels= [y for y in df['X2'].value_counts().sort_values(ascending= False).head(10).index]

In [26]:
top_10_labels

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [27]:
# get whole set of dummy variables, for all the categorical variables
def OHE_top_x(df, variable, top_x_labels):
        # function to create the dummy variables for the most frequent labels
        # we can vary the number of most frequent labels that we encode
    
    for label in top_10_labels:
        df[variable+''+label]= np.where(df[variable]== label, 1, 0)

In [29]:
# read the data again
df = pd.read_csv('data/mercedesbenz.csv', usecols=['X1', 'X2'])

In [30]:
#encode X2 into the most top 10 frequent categories
OHE_top_x(df,'X2', top_10_labels)
df.head(10)

  X1  X2  X2as  X2ae  X2ai  X2m  X2ak  X2r  X2n  X2s  X2f  X2e
0  v  at     0     0     0    0     0    0    0    0    0    0
1  t  av     0     0     0    0     0    0    0    0    0    0
2  w   n     0     0     0    0     0    0    1    0    0    0
3  t   n     0     0     0    0     0    0    1    0    0    0
4  v   n     0     0     0    0     0    0    1    0    0    0
5  b   e     0     0     0    0     0    0    0    0    0    1
6  r   e     0     0     0    0     0    0    0    0    0    1
7  l  as     1     0     0    0     0    0    0    0    0    0
8  s  as     1     0     0    0     0    0    0    0    0    0
9  b  aq     0     0     0    0     0    0    0    0    0    0